### ISSUE TITLE
Temporary addition of GNU 7.3 to GHA

### ISSUE THREAD

**Issue by odlomax** [ecmwf/atlas#136]
### Compiler support

As previously discussed, the Met Office has a temporary requirement where we have to make sure that Atlas builds and runs using GNU 7.3 compilers.

GNU 7.3 supports all of the C+17 language additions and most of the standard library additions, so the impact on Atlas should be minimal. [Supported features](https://en.cppreference.com/w/cpp/compiler_support/17).

We currently believe we should be able to remove this requirement over the next six to twelve months.

**Comment by tlmquintino** [comment]
Thanks for this info. @wdeconinck I think we must then also add this to the rest of the stack.
Can you please liaise with @dtip  ?

**Comment by wdeconinck** [comment]
@tlmquintino if you think that is necessary. Otherwise I can add just a few lines in the older atlas GitHub actions that I till have that uses Github-owned runners, for the remaining 6 months or so. Depends how deep the UKMO wants this requirement to be.

**Comment by odlomax** [comment]
> @tlmquintino if you think that is necessary. Otherwise I can add just a few lines in the older atlas GitHub actions that I till have that uses Github-owned runners, for the remaining 6 months or so. Depends how high in the stack the UKMO wants this requirement to be.

@tlmquintino @wdeconinck 

Thanks for getting back. UKMO is basically restricted to GNU 7.3 until we're fully up and running with with our new HPC -- that should happen by the end of this year. 

We're currently using the following ECMWF packages in our JEDI work with JCSDA:
  * eckit
  * fckit
  * atlas
  * fiat
  * ectrans
  * odc
  
Our main concern is that some exotic parts of C++17 might slip into Atlas/eckit/fckit and we lose our capability to run it on the HPC. Once we're on the new HPC, this problem goes away. (until we start having fun with C++20...)

**Comment by tlmquintino** [comment]
@wdeconinck since this involves eckit and odc too I would prefer this is done in the new CI/CD framework.
Please liaise with @dtip or @figi44 to inject GNU 7.3 in our build matrix.

**Comment by yaswant** [comment]
Thank you @wdeconinck - is there any way we can set minor version to 3?  Its not required from CXX17 perspective and not relevant in the scope of the current discussion.  Sharing this for information only.

Fortran-mpi related complication: F2018 features needed to support the build of the `mpi_f08` module - we cant build this module with mpich or openmpi in gcc-7.3 environment.  And this is the gnu compiler version we are stuck with current Cray.

**Comment by wdeconinck** [comment]
@yaswant It seems not trivial to install gcc-7.3 when the default 'gcc-7' is 7.5 (see https://askubuntu.com/questions/1225026/how-can-i-install-a-specific-version-of-gcc-on-ubuntu-18-04)
The route is probably compiling a specific gcc version manually.
I'll leave that for the newer custom CI/CD self-hosted runners that are being developed.

Which code is using the mpi_f08 module?

**Comment by yaswant** [comment]
@wdeconinck no problem. 

My colleague was testing `mpi_f08` module in ops based JEDI interface for the UM (`ops-um-jedi`).  If I understand correctly `fckit` does not support shared memory so he used raw mpi there[^1].   It is unlikely that anyone using `fckit` will be doing that.

[^1]:  We are delaying this implementation for now.

**Comment by tlmquintino** [comment]
Looking at the release notes for GCC 7.3 to 7.5 it looks like they were only bug fixes.
See https://gcc.gnu.org/gcc-7/changes.html

So unless you want to reproduce buggy behaviour, I would argue that using 7.5 is a very good proxy to using 7.3 _for the purposes of ensuring the builds dont break and unit tests are passing_.

**Comment by wdeconinck** [comment]
As some fluke experience in recent pull-request showed (see #145), the gnu 7.5 had a c++ compiler bug fixed compared to 7.3.
That shows that we cannot fully rely on the gnu-7.5.

**Comment by dtip** [comment]
We're now testing the ECMWF stack with gnu 7.3.1 on CentOS 7.9

PR: https://github.com/ecmwf-actions/downstream-ci/pull/14

Shout if you run into any issues.

**Comment by odlomax** [comment]
> We're now testing the ECMWF stack with gnu 7.3.1 on CentOS 7.9
> 
> PR: [ecmwf-actions/downstream-ci#14](https://github.com/ecmwf-actions/downstream-ci/pull/14)
> 
> Shout if you run into any issues.

Thanks @dtip, @wdeconinck, @tlmquintino!
