### ISSUE TITLE
ctest failure in atlas_fctest_unstructuredgrid

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/atlas#143]
### What happened?

Building atlas and running the  ctests gives this:

52: Test command: /home/h01/frwd/cylc-run/AtlasFailure/share/build-mo-spice_gnu_debug/atlas/src/tests/grid/atlas_fctest_unstructuredgrid
52: Working Directory: /home/h01/frwd/cylc-run/AtlasFailure/share/build-mo-spice_gnu_debug/atlas/src/tests/grid
52: Environment variables: 
52:  OMP_NUM_THREADS=1
52: Test timeout computed to be: 10000000
52: /spice/scratch/frwd/cylc-run/AtlasFailure/share/mo-bundle/atlas/src/tests/grid/fctest_unstructuredgrid.F90:228: warning: FCTEST_CHECK_EQUAL( grid%owners(), 2 )
52:  --> [           1 !=           2 ]
52: STOP 1

### What are the steps to reproduce the bug?

Building atlas and running the ctests, I am also using head of develop of eckit and fckit.

### Version

head of develop

### Platform (OS and architecture)

Linux & Cray, gcc

### Relevant log output

```shell
52: Test command: /home/h01/frwd/cylc-run/AtlasFailure/share/build-mo-spice_gnu_debug/atlas/src/tests/grid/atlas_fctest_unstructuredgrid
52: Working Directory: /home/h01/frwd/cylc-run/AtlasFailure/share/build-mo-spice_gnu_debug/atlas/src/tests/grid
52: Environment variables: 
52:  OMP_NUM_THREADS=1
52: Test timeout computed to be: 10000000
52: /spice/scratch/frwd/cylc-run/AtlasFailure/share/mo-bundle/atlas/src/tests/grid/fctest_unstructuredgrid.F90:228: warning: FCTEST_CHECK_EQUAL( grid%owners(), 2 )
52:  --> [           1 !=           2 ]
52: STOP 1
```

### Organisation

Met Office

**Comment by wdeconinck** [comment]
Thank you @DJDavies2 for this report. I will investigate.

**Comment by wdeconinck** [comment]
Commit [d69e61a](https://github.com/ecmwf/atlas/commit/d69e61aca4fb0a6f976e6a429c34ea7fe471f5b2) fixes this issue. Thanks again for reporting!

**Comment by DJDavies2** [comment]
Thanks, it works for me now.

There may be more issues coming though.
