### ISSUE TITLE
Interpolation::NonLinear datatype incompatible with atlas::Fieldsets of heterogeneous types

### ISSUE THREAD

**Issue by twsearle** [ecmwf/atlas#173]
### Is your feature request related to a problem? Please describe.

I would like to be able to have an atlas fieldset that contains a mix of types, both float fields and double fields. However, I hit an issue when it comes to interpolating fields that contain missing values.

At configuration time, I need to configure my atlas interpolator for my entire fieldset. The only way to configure the `Missing` adjuster for the interpolation weights is at this time, using a configuration that is passed into a builder here:
https://github.com/ecmwf/atlas/blob/8780370562c89ea81cf302d7aba72476844759c8/src/atlas/interpolation/nonlinear/Missing.cc#L30

However, this configurations holds globally for all fields in the fieldset, meaning that they all must have a matching type. If this is not the case, an error is thrown when attempting to construct a field-view of an incompatible datatype:
https://github.com/ecmwf/atlas/blob/4e2a05546bd32ed6762da9fcf69ca4a1978dc72e/src/atlas/interpolation/nonlinear/NonLinear.h#L71

For example, using `missing-if-all-missing` requires all fields to be interpolated are doubles. Using `missing-if-all-missing-real32`  requires all fields to be interpolated are floats.

### Describe the solution you'd like

I think ideally, the missing values object datatype would be configured based on the runtime atlas field type, rather than on the configuration string passed to the factory. This would have two benefits I think:
1. The methods used would depend solely on the type of the atlas::Field, and so be determined in one place. This lends clarity - in my program at the moment the configuration has two sections which both must be updated depending on the type of the atlas::Field you select.
2. It would be possible to have fieldsets containing a mix of double and float fields, which would be useful for performance and precision when required.

### Describe alternatives you've considered

1. update the atlas interpolator configuration at runtime based on the field types selected
   - This isn't trivial to do, given the high level layout of the JEDI-OOPS framework
   - This doesn't solve my second issue of wanting a mix of Float and Double types in a fieldset
2. Use multiple field sets and multiple interpolators with different configurations
   - Its possible this is the way forward, although it would incur a memory and performance cost, as I would have to setup essentially the same interpolation object more than once.
3. Keep all Fields in my program of a consistent type.
   - This is my approach at the moment, however I have found that I needed to switch from double to float to fit the program in memory, and I am concerned future data (ocean colour is log distributed for example) might be sensitive to the move from double to float.

### Additional context

https://github.com/MetOffice/orca-jedi/issues/78

### Organisation

Met Office

**Comment by wdeconinck** [comment]
Hi @twsearle it seems like a good idea. I think the "missing" can be made to work for multiple data types in a more generic way, by introspecting each field's data type.
