### ISSUE TITLE
Cannot find ectrans header

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/atlas#177]
### What happened?

Trying to build atlas against ectrans (head of develop) gives this compile failure:

/home/h01/frwd/cylc-run/mi-be984/work/1/git_clone_atlas/atlas/src/atlas/library/Library.cc:63:10: fatal error: ectrans/transi.h: No such file or directory
   63 | #include "ectrans/transi.h"
      |          ^~~~~~~~~~~~~~~~~~

### What are the steps to reproduce the bug?

Compile atlas with -DATLAS_ENABLE_ECTRANS=ON.  Ectrans has been installed and ecbuild claims to have found it.

### Version

head of develop

### Platform (OS and architecture)

Linux.

### Organisation

Meto

**Comment by DJDavies2** [comment]
This is perhaps more of an ectrans problem than an atlas problem.  Doing ls -l on the ectrans include/ectrans directory gives this:

-rw-r--r--. 1 frwd users 6524 Feb 18 17:07 dir_trans.h
-rw-r--r--. 1 frwd users 6370 Feb 18 17:07 dir_transad.h
-rw-r--r--. 1 frwd users 2084 Feb 18 17:07 dist_grid.h
-rw-r--r--. 1 frwd users 2044 Feb 18 17:07 dist_grid_32.h
-rw-r--r--. 1 frwd users 2205 Feb 18 17:07 dist_spec.h
-rw-r--r--. 1 frwd users 1998 Feb 18 17:07 gath_grid.h
-rw-r--r--. 1 frwd users 2013 Feb 18 17:07 gath_grid_32.h
-rw-r--r--. 1 frwd users 2277 Feb 18 17:07 gath_spec.h
-rw-r--r--. 1 frwd users 1375 Feb 29 17:07 get_current.h
-rw-r--r--. 1 frwd users 2292 Feb 18 17:07 gpnorm_trans.h
-rw-r--r--. 1 frwd users 3030 Feb 29 17:07 ini_spec_dist.h
-rw-r--r--. 1 frwd users 8022 Feb 18 17:07 inv_trans.h
-rw-r--r--. 1 frwd users 7809 Feb 18 17:07 inv_transad.h
-rw-r--r--. 1 frwd users 4558 Feb 18 17:07 setup_trans.h
-rw-r--r--. 1 frwd users 3641 Feb 29 17:07 setup_trans0.h
-rw-r--r--. 1 frwd users 1942 Feb 18 17:07 specnorm.h
-rw-r--r--. 1 frwd users 1450 Feb 18 17:07 sugawc.h
-rw-r--r--. 1 frwd users 1134 Feb 18 17:07 trans_end.h
-rw-r--r--. 1 frwd users 8287 Feb 18 17:07 trans_inq.h
-rw-r--r--. 1 frwd users 1749 Feb 18 17:07 trans_pnm.h
-rw-r--r--. 1 frwd users  570 Feb 18 17:07 trans_release.h
lrwxrwxrwx. 1 frwd users   14 Mar  6 12:59 transi.h -> ../../transi.h
lrwxrwxrwx. 1 frwd users   15 Mar  6 12:59 version.h -> ../../version.h
-rw-r--r--. 1 frwd users 2174 Feb 18 17:07 vordiv_to_uv.h

Those symbolic links don't exist.

**Comment by DJDavies2** [comment]
See https://github.com/ecmwf-ifs/ectrans/issues/68.

**Comment by wdeconinck** [comment]
Thanks @DJDavies2 you're very right.
