### ISSUE TITLE
Risk of surprising behavior when adding multiple Fields of same name into FieldSet

### ISSUE THREAD

**Issue by fmahebert** [ecmwf/atlas#194]
### What happened?

It's possible to add multiple Fields sharing the same name into one FieldSet. This is already surprising, because it's not immediately clear that `fieldset[name]` would be well defined.

Looking through the code, I believe it _is_ well-defined in the current implementation: the `FieldSetImpl::add` method updates the FieldSet's internal mapping `index_` from names to indices to add the name of the new Field being added; but when that name is a duplicate, the result is to update the map element to point to a new index instead of _adding_ a new map element. See here,
https://github.com/ecmwf/atlas/blob/55e20456d5f754e9d6e1180d8db5fa866010bf3b/src/atlas/field/FieldSet.cc#L59

The result is that the most-recently-inserted Field with some name will be the one returned by `fieldset[name]`. See reproducer below.

This opens the door for various inconsistencies. For example,
```
for (const auto & name : fieldset.field_names()) {
  auto & field = fieldset[name];
}
```
will not actually loop over all Fields — if there's a N-fold duplicate name it will hit the most-recently-inserted Field N times.

Is allowing duplicate Fields of the same name intentional? I believe the code would be safer if this were simply forbidden.

### What are the steps to reproduce the bug?

Here's code that shows that the most-recently-inserted Field is the one returned
```
#include <iostream>
#include "atlas/field.h"
#include "atlas/functionspace.h"
#include "atlas/grid.h"
#include "atlas/util/Config.h"
#include "eckit/runtime/Main.h"

int main(int argc, char **argv) {
  using namespace atlas;
  eckit::Main::initialise(argc, argv);

  const Grid grid("N16");
  const functionspace::StructuredColumns fs(grid);

  Field f1 = fs.createField<double>(option::name("name") | option::levels(1));
  Field f2 = fs.createField<double>(option::name("name") | option::levels(2));
  Field f3 = fs.createField<double>(option::name("name") | option::levels(3));
  FieldSet fieldset;
  fieldset.add(f1);
  fieldset.add(f2);
  fieldset.add(f3);
  for (const auto & name : fieldset.field_names()) {
    std::cout << "field: " << name << " has levels: " << fieldset[name].levels() << std::endl;
  }

  return 0;
}
```

### Version

0.35

### Platform (OS and architecture)

macOS

**Comment by MarekWlasak** [comment]
@fmahebert I think this is intentional behaviour - the primary most native access is by index number.  Saying that it would be great if the mapping of strings to index number could be extended to (field name + field meta data) -> field set index. 
@wdeconinck  would such an extension be welcome?

**Comment by fmahebert** [comment]
@MarekWlasak as long as the available accessors are unambiguous, I think the issue of "risk of surprising behavior" would be addressed. If that means the name-based accessor becomes `fieldset.field(name, <some metadata>)`... then that's notably less elegant, but I'd prefer that over ambiguous.

**Comment by svahl991** [comment]
Hello. I'm wondering about the status of this issue. Thanks.

**Comment by wdeconinck** [comment]
TL,DR:
The safest way to iterate fields is definitely by index, or better using the built-in iterator:
```c++
for (const Field& field : fieldset){
    std::cout << "field: " << field.name() << " has levels: " << field.levels() << std::endl;
}
```
---
This is a quite difficult issue to solve.
It is also related to previously solved issue https://github.com/ecmwf/atlas/issues/147 where renaming a field was initially not updating its name registered in the FieldSet map. That was solved by registering the FieldSet as an observer to name changes of its fields and updating its internal map.

Do we want to abort when unnamed fields are added to a fieldset?
Not sure if following is a good idea, but we could probably add a method like this, where a field gets registered with a name which is unrelated to its owned name.
```
void FieldSet::add("fieldset_specific_fieldname", Field);
```
With this API we could abort when the names are not unique upon insertion, and we never update this name, even when a field gets renamed internally. There may still be inconsistencies though...

**Comment by wdeconinck** [comment]
@svahl991 I think that is indeed the best course of action.
Accessing ```fieldset[name]``` will throw exception if multiple fields with same name exist.

**Comment by wdeconinck** [comment]
@fmahebert @svahl991 please check if  PR #210 is a satisfactory solution.

**Comment by svahl991** [comment]
Yes, I think that is a great improvement! Thanks for creating this. I would think users would still want to avoid duplicate names in most situations so that the name accessor works, but at least this prevents the possibility of the "silent" error when it does not.

I'm not sure if you're still working on the PR, but I feel it might be good to have a test that validates that the new increment/decrement logic for `duplicates_` in the `onFieldRename` method works as expected.

**Comment by wdeconinck** [comment]
@svahl991 thanks for feedback.
The test to check for this rename was already present in this PR. Please check it matches your expectation.

**Comment by svahl991** [comment]
> The test to check for this rename was already present in this PR. Please check it matches your expectation.

Ah, I did miss that a rename is called in the test to clear the duplicate. I guess to be a little nitpicky, it appears that the logic where a duplicate name is created through a rename is not specifically being tested. (The duplicate in the test is created through an `add` which is a separate code.)
