### ISSUE TITLE
Missing halos after calling build_halo on a "structured" mesh

### ISSUE THREAD

**Issue by fmahebert** [ecmwf/atlas#200]
### What happened?

(preface: I understand that the preferred way to do geometric computations with a StructuredGrid is often via the grid itself or a StructuredColumns FunctionSpace. But I'm trying to write a piece of code that will generically work with any FunctionSpace, therefore the computations are more easily done on the mesh)

If I pass a StructuredGrid to a StructuredMeshGenerator, then call the `build_halo` action on the resulting Mesh, I find the halos were not added uniformly to the Mesh partitions. The Mesh appears to be broken at the lon=0 meridian.

See the figures below illustrating how there are no halos extending to the left or right across the lon=0 meridian. This is from code below. These figures are a little busy, so here is the key:
- in (light/dark) blue rings, are the points of the corresponding StructuredColumns FunctionSpace's `.lonlat()` field, with color denoting owned/ghost
- in (light/dark) orange dots, are the points of the `mesh.nodes().lonlat()` Field from the StructuredMeshGenerator, with color denoting owned/ghost (halo=0)
- in black dots, are the points added to the Mesh by `build_halo(mesh, 1)`. As expected there is an extra halo of ghost points added, _except_ across the meridian.

![fig_global_structured_mesh_vs_fs_4-1](https://github.com/ecmwf/atlas/assets/881747/4629e622-b06d-49a6-9f75-6c0713246e73)
![fig_global_structured_mesh_vs_fs_4-2](https://github.com/ecmwf/atlas/assets/881747/c2330d8d-9974-4837-8b59-712921d96c8c)

In contrast, passing the StructuredGrid to a DelaunayMeshGenerator, then calling `build_halo`, produces a Mesh whose halo does grow across the meridian as one would expect:

![fig_global_delaunay_mesh_vs_fs_4-1](https://github.com/ecmwf/atlas/assets/881747/f7c5908f-a52b-447c-8942-108fb8f1cda2)
![fig_global_delaunay_mesh_vs_fs_4-2](https://github.com/ecmwf/atlas/assets/881747/993c165b-c66c-4b8b-9b39-58301987abc1)

Is this behavior — the inconsistent result of calling `build_halo` when the mesh came from a StructuredMeshGenerator —  a feature or a bug?

### What are the steps to reproduce the bug?

```
    util::Config gridconf{};
    gridconf.set("type", "regular_gaussian");
    gridconf.set("N", 15);
    StructuredGrid grid(gridconf);

    atlas::grid::Partitioner part("equal_regions");
    Mesh mesh = MeshGenerator("structured").generate(grid, part);
    mesh::actions::build_halo(mesh, 1);

    util::Config fsconf{};
    fsconf.set("halo", 1);
    functionspace::StructuredColumns fs(grid, part, fsconf);

    // write mesh points to file
    {
      auto lonlat = array::make_view<double, 2>(mesh.nodes().lonlat());
      auto ghost = array::make_view<int, 1>(mesh.nodes().ghost());
      std::ofstream meshout("mesh_points.dat");
      for (int i = 0; i < ghost.shape(0); ++i) {
        meshout << lonlat(i, 0)
          << " " << lonlat(i, 1)
          << " " << ghost(i)
          << std::endl;
      }
    }

    // write FS points to file
    {
      auto lonlat = array::make_view<double, 2>(fs.lonlat());
      auto ghost = array::make_view<int, 1>(fs.ghost());
      std::ofstream fsout("fs_points.dat");
      for (int i = 0; i < ghost.shape(0); ++i) {
        fsout << lonlat(i, 0)
          << " " << lonlat(i, 1)
          << " " << ghost(i)
          << std::endl;
      }
    }
```

### Version

0.37

### Platform (OS and architecture)

macOS 14.5, intel i5

**Comment by wdeconinck** [comment]
Hi @fmahebert, sorry for the long delay in response. We are using StructuredGrid with StructuredMeshGenerator all the time, so that is perfectly OK to expect this to work.
The issue here is that some function calls are missing before `build_halo`:
```c++
mesh::actions::build_nodes_parallel_fields(mesh);
mesh::actions::build_periodic_boundaries(mesh); // this one marks boundaries as periodic for following
mesh::actions::build_halo(mesh, 1);
```
Normally this is done within `atlas::functionspace::NodeColumns` constructor:
https://github.com/ecmwf/atlas/blob/develop/src/atlas/functionspace/NodeColumns.cc#L210-L224
So you could have instead just created this functionspace as well.

**Comment by fmahebert** [comment]
Hi @wdeconinck — I can confirm that using these additional mesh actions gives the expect behavior out of the build_halo actions.

Thank you for the suggestion!

I'll close this, as the issue is resolved from my perspective.
