### ISSUE TITLE
Native WrappedDataStore can leak device memory

### ISSUE THREAD

**Issue by l90lpa** [ecmwf/atlas#234]
### What happened?

First, I'm assuming that the intended semantics of `atlas::array::native::WrappedDataStore` are that it has a non-owning handle to host memory, and has an **owning** handle to device memory (if allocated).

In the class's current form, the class only has an implicit default destructor. Therefore, if there is allocated device memory on a class instance at the time of its destruction this device memory is leaked because there is no deallocation performed.

A fix might be to add:
```
~WrappedDataStore() {
    deallocateDevice();
}
```
to the class.

### What are the steps to reproduce the bug?

Build Atlas with CUDA support enabled and OpenACC support disabled, then do something like:

```c++
#include "atlas/array/native/NativeDataStore.h"
...
int data[10];
{
    atlas::array::native::WrappedDataStore<int> ds(data, 10);
    ds.allocateDevice();
} // <-- memory leak here after ~WrappedDataStore()
```

### Version

develop

### Platform (OS and architecture)

Ubuntu 22.04

### Organisation

JCSDA

**Comment by wdeconinck** [comment]
Hi yes you're correct! I will fix this immediately. Thanks for reporting.
