### ISSUE TITLE
Required ECKIT version

### ISSUE THREAD

**Issue by benjaminmenetrier** [ecmwf/atlas#238]
### What happened?

ATLAS compilation is failing with ECKIT < 1.26.0, this should be updated in the main `CMakeLists.txt`.

### What are the steps to reproduce the bug?

Compile ATLAS with any older version.

### Version

develop

### Platform (OS and architecture)

any

### Organisation

Norwegian Meteorological Institute

**Comment by wdeconinck** [comment]
Hi @benjaminmenetrier I had also noticed this and had fixed this with commit 3de936140.
Atlas version 0.40.0 has been released, and I have tested it still works with eckit 1.16.0
