### ISSUE TITLE
atlas_fctest_grids failure

### ISSUE THREAD

**Issue by DJDavies2** [ecmwf/atlas#65]
atlas_fctest_grids fails as follows:

/spice/scratch/frwd/cylc-run/AtlasFailure/share/lfric-bundle/atlas/src/tests/grid/fctest_grids.F90:64: warning: FCTEST_CHECK_EQUAL( spec%json(), '{"domain":{"type":"global"},"name":"O32","projection":{"type":"lonlat"}}' )
 --> [{"name":"O32","domain":{"type":"global"},"projection":{"type":"lonlat"}}!=
 {"domain":{"type":"global"},"name":"O32","projection":{"type":"lonlat"}}]

Atlas version 0.23.0.  It looks like the string representation of a dictionary type structure is being generated with the elements in a different order leading to a string comparison failing although eyeballing the elements suggests they are in fact the same.

**Comment by wdeconinck** [comment]
This is due to a change in eckit. The printed order is now matching the order of creation.
I have fixed this test to be more robust in commit 70aa3ec659e which is already present in version 0.24.0
You could just ignore the failed test however as, like you said, there is no difference in content.

**Comment by DJDavies2** [comment]
Thanks, updating to 0.24.0 fixes this.
